[build]
command = "sed -i \"s|REDIRECT_PLACEHOLDER|${PROD_API_LOCATION}|g\" netlify.toml && npm run build"

[[redirects]]
  from = "/api/*"
  to = "REDIRECT_PLACEHOLDER/api/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

